### ISSUE TITLE
Bug in normalize

### ISSUE THREAD

**Issue by danielhorn** [berndbischl/BBmisc#51] opened 2015-06-16 14:10 UTC
Doku says:
For data.frames, only the numeric columns are touched, all others are left unchanged.

But normalize(iris) drops the class col, all non-numeric cols seems to be dropped.

Can I fix it? Or do you want the function to drop non-numeric cols?

**Comment by jakob-r** [comment] 2015-06-16 14:18
Yes. Fix would be nice. It even says so in the description *For data.frames, only the numeric columns are touched, all others are left unchanged.* 
So it doesn't work as intended.
Note: We call that function in `mlr::normalizeFeatures` where me already make sure that it only deals with numerics.

**Comment by danielhorn** [comment] 2015-06-16 14:36
That why I'm wondering. It feels like a major bug - droping all non-numeric cols. But nobody noticed it yet ...

In the belonging unit test I found this code:

y = normalize(iris, method = "range", range = c(3, 4))
y[, 5L] = iris$Specis

I fixed everything ...

**Comment by berndbischl** [comment] 2015-06-16 15:32
Is this fixed now? OR should I do it?

**Comment by berndbischl** [comment] 2015-06-16 15:32
Daniel seems assigned.

**Comment by jakob-r** [comment] 2015-06-16 15:35
Fixed by @danielhorn commit b94abcbb929c24c93818c67a423d7a5e3ca88bbf

**Closed by jakob-r** 2015-06-16 15:35 UTC
